var type_names={A:{icon:"新",name:"新番組"},
B:{icon:"再",name:"再放送"},
C:{icon:"終",name:"最終回"},
D:{icon:"手",name:"手話通訳放送"},
E:{icon:"字",name:"字幕放送"},
F:{icon:"双",name:"双方向放送"},
G:{icon:"デ",name:"番組連動データ放送"},
H:{icon:"S",name:"ステレオ放送"},
I:{icon:"二",name:"二ヶ国語放送"},
J:{icon:"多",name:"音声多重放送"},
K:{icon:"解",name:"音声解説"},
L:{icon:"SS",name:"サラウンドステレオ"},
M:{icon:"B",name:"圧縮Bモードステレオ"},
N:{icon:"N",name:"ニュース"},
O:{icon:"天",name:"天気予報"},
P:{icon:"交",name:"交通情報"},
Q:{icon:"映",name:"劇場映画"},
R:{icon:"料",name:"有料放送"},
S:{icon:"前",name:"前編"},
T:{icon:"後",name:"後編"},
U:{icon:"初",name:"初回放送"},
V:{icon:"生",name:"生放送"},
W:{icon:"HV",name:"ハイビジョン放送"},
X:{icon:"PV",name:"Pay Per View"},
Y:{icon:"PS",name:"Pay Per Series"},
Z:{icon:"吹",name:"吹き替え"},
a:{icon:"契",name:"契約"},
b:{icon:"幕",name:"字幕スーパー"},
c:{icon:"無",name:"無料"},
d:{icon:"PG12",name:"PG12指定"},
e:{icon:"R15",name:"R15指定"},
f:{icon:"4K",name:"4K"},
g:{icon:"HDR",name:"HDR"},
h:{icon:"5.1ch",name:"5.1ch"},
i:{icon:"8K",name:"8K"},
j:{icon:"22.2ch",name:"22.2ch"}};